### ISSUE TITLE
Should we use label/altLabel instead of preferredName/variantName?

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-authorities#12]
We consistently use label/altlabel in lobid-resources and lobid-organisations and, thus, should probably also use it in lobid-authorities...

**Comment by fsteeg** [comment]
In resources, we have label/altLabel, but in organisations we use name/alternateName for the main entities. Since we said we'll stay close to the GND data, I vote sticking with preferredName/variantName.

**Comment by acka47** [comment]
> In resources, we have label/altLabel, but in organisations we use name/alternateName for the main entities.

Yes, for the main entities. But for entities from an authority file or controlled vocaulary we use label/altLabel. And GND is an authority file.... Also, we use  label/altLabel in lobid-resources for the very same resources we have in authorities. This means, if we stick to the GND properties, we will have different (inconsistent but not contradictory) name/variant name properties in lobid-resources and lobid-authorities for the same thing.

Noam Chomsky in lobid-authories:

```json
{
   "id":"http://d-nb.info/gnd/118520520",
   "preferredName":[
      "Chomsky, Noam"
   ],
   "variantName":[
      "Чомски, Ноам",
      "Shūmskī, Nuʿūm",
      "Chomsky, Noam A.",
      "Chomsky, Abraham Noam",
      "Chomski, N. A."
   ]
}
```
Information on Noam Chomsky from http://lobid.org/resources/TT002133009.json:

```json
{
   "id":"http://d-nb.info/gnd/118520520",
   "label":"Chomsky, Noam",
   "altLabel":[
      "Chomsky, Avram N.",
      "Chomsky, A.",
      "Shūmskī, N.",
      "Хомский, Наум",
      "Chomusukī, N.",
      "Chomski, N. A."
   ],
   "type":[
      "Person"
   ]
}
```

There is no perfect solution for this. Although this means having some inconsistencies within lobid, I agree with @fsteeg that we should not start altering the GND further than adding some implicit meaning. Thus, I am ok with sticking to preferredName/variantName. Closing.
