### ISSUE TITLE
Add 2nd level GND typing

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-authorities#2]
From https://github.com/hbz/lobid-authorities/issues/1#issuecomment-312597639:

> Furthermore, we should have a type from the second level of GND ontology attached to each resource. We will need this for facetting. GND ontology has three levels in it stype hierarchy (except for Person, where we have a fourth one added). see the overview over the GND class hierarchy at https://wiki1.hbz-nrw.de/x/CIeW. In the concrete example, `PlaceOrGeographicName` should be in the data.

**Comment by fsteeg** [comment]
Deployed to test: http://test.lobid.org/authorities/4074335-4.json

(@ChristophEwertowski: We have no production system yet, so just +1 and close if this looks good.)

**Comment by ChristophEwertowski** [comment]
+1
