### ISSUE TITLE
Use general preferredName / variantName properties

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-authorities#3]
From #1:

> We don't want specific name properties like `preferredNameForThePlaceOrGeographicName` and `variantNameForThePlaceOrGeographicName`. For all entities, we should just use `preferredName` and `variantName`.

> This will allow us to query the whole data in a uniform way. (The type is made clear by other means so that we don't need the specific properties.)

**Comment by fsteeg** [comment]
Deployed to test: http://test.lobid.org/authorities/4074335-4.json

(@ChristophEwertowski: We have no production system yet, so just +1 and close if this looks good.)

**Comment by ChristophEwertowski** [comment]
+1
