### ISSUE TITLE
Remove blank node ids

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-authorities#4]
From https://github.com/hbz/lobid-authorities/issues/1#issuecomment-312588435:

> Re. the framing output from http://tinyurl.com/ychm4t92, I just noticed that blank nodes get an `id`: 
>
> ~~~json
>      "hasGeometry": {
>        "@id": "_:b0",
>        "@type": "http://www.opengis.net/ont/sf#Point",
>        "asWKT": "Point ( -000.125740 +051.508530 )"
>      }
>~~~
>
> We should get rid of them. This has already been addressed in the JSON-LD Framing [spec 1.1](https://json-ld.org/spec/latest/json-ld-framing/) ("pruneBlankNodeIdentifiers") but is currently only implemented in the Ruby library, see https://github.com/json-ld/json-ld.org/issues/293.

**Comment by fsteeg** [comment]
Deployed to test: http://test.lobid.org/authorities/4074335-4.json

**Comment by acka47** [comment]
+1
