### ISSUE TITLE
Index our JSON-LD in Elasticsearch

### ISSUE THREAD

**Issue by fsteeg** [hbz/lobid-authorities#5]
Test indexing the format from #1 in Elasticsearch.

**Comment by fsteeg** [comment]
Basic full dump conversion (~6 hours) and indexing (~30 minutes) works.

Current issues:

- [ ] Convert: "Character reference "&#55396" is an invalid XML character" in http://d-nb.info/gnd/1072719991 (also with XML 1.1 header)
- [ ] Index: Varying types for academicDegree, dateOfBirth, dateOfDeath (also with disable data detection)
- [ ] Index: Missing context entries resulting in invalid field names (SKOS broadMatch, exactMatch, relatedMatch)

Further TODOs:

- [ ] Use index in GET requests
- [ ] Implement simple search route
- [ ] Extract config strings to application.conf
- [ ] Set up tests
- [ ] Set up Travis
- [ ] Update README

**Comment by fsteeg** [comment]
Indexing error log: [index-errors-2017-07-07.txt](https://github.com/hbz/lobid-authorities/files/1131249/index-errors-2017-07-07.txt)

**Comment by fsteeg** [comment]
Added search and direct access based on our index. Deployed to http://test.lobid.org/authorities.

**Comment by fsteeg** [comment]
Full conversion took 7.6 hours locally. Two errors, both invalid character references:

[convert-errors-2017-07-11.txt](https://github.com/hbz/lobid-authorities/files/1139963/convert-errors-2017-07-11.txt)

**Comment by fsteeg** [comment]
Newest indexing error log: [index-errors-2017-07-12.txt](https://github.com/hbz/lobid-authorities/files/1141336/index-errors-2017-07-12.txt) (21095 failing records)

**Comment by fsteeg** [comment]
The two records with invalid XML characters have been fixed in the GND by Isabell.

We'll get them when we use a new dump, or when we implements updates.

**Comment by fsteeg** [comment]
Deployed to test: http://test.lobid.org/authorities

(@acka47: For details on how we're dealing with field types issues that we discussed see 2cb4b9be8bc2020c96bc373473db2c7ae6b3bf2c)

**Comment by acka47** [comment]
The current total number of GND resources (14,022,171) already looks much better than the total number in API 1.x (13,498,866, see http://lobid.org/subject?q=*&format=full). Very good.

The data also looks very good. Closing.
