### ISSUE TITLE
Enable filtering based on GND ontology types

### ISSUE THREAD

**Issue by acka47** [hbz/lobid-authorities#8]
_Moved here with some adjustments from https://github.com/lobid/lodmill/issues/447._

Example query: "heinsberg"

Facets/possibilities for filtering by secend-level types:
- Person
- Subject Heading
- Place or Geographic Name
- Converence or Event
- Family
- Corporate Body
- Work

(Similar to e.g. https://portal.dnb.de/opac.htm?method=simpleSearch&query=heinsberg)

Clicking a facet should yield filtered search results with sub-facets, e.g.:

Place or Geographic Name:
- Building or Memorial
- Administrative Unit
- Fictive Place
- ...

**Comment by fsteeg** [comment]
Deployed to test: http://test.lobid.org/authorities/search

**Comment by ChristophEwertowski** [comment]
The type "Family" is missing at the collection of second-level types. And drilling-down facets isn't implemented right, see [query](http://test.lobid.org/authorities/search?q=*+AND+type:%22Person%22&from=0&size=10) where are "Works" under "Persons".

**Comment by fsteeg** [comment]
> The type "Family" is missing at the collection of second-level types.

Fixed on test: http://test.lobid.org/authorities/search

> And drilling-down facets isn't implemented right, see query where are "Works" under "Persons".

The faceted search shows all types for the selected result list, which has entries with both _Work_ and _Person_. If that's not right it's a data issue in the GND, see e.g. http://d-nb.info/gnd/1049620550

**Comment by ChristophEwertowski** [comment]
Mmh, I searched for the person of the example and filtered it for Person at the GND. After this there is no possiblity to filter with other facets. So I think it's okay. Anyhow I'm assigning it to acka47 because I'm not sure I understood it right.

**Comment by acka47** [comment]
+1

The problems mentioned are due to obviously incorrect typing in the GND (see e.g. http://test.lobid.org/authorities/search?q=%22Dialogues+socratiques+ou+entretiens+sur+divers+sujets+de+morale%22).

**Comment by acka47** [comment]
Closing.
